import { z } from "zod";

export const DepartmentMenuVisibilitySchema = z.object({
  dashboard: z.boolean(),
  erp: z.boolean(),
  erp_time_control: z.boolean(),
  erp_tasks: z.boolean(),
  erp_projects: z.boolean(),
  erp_external_collaborations: z.boolean(),
  erp_simulations: z.boolean(),
  erp_invoices: z.boolean(),
  work_management: z.boolean(),
  work_contracts: z.boolean(),
  work_comparatives: z.boolean(),
  work_worksites: z.boolean(),
  work_providers: z.boolean(),
  legal: z.boolean(),
  legal_contracts: z.boolean(),
  administration_department: z.boolean(),
  administration_contracts: z.boolean(),
  administration_worksites: z.boolean(),
  administration_providers: z.boolean(),
  hr: z.boolean(),
  hr_departments: z.boolean(),
  hr_employees: z.boolean(),
  hr_positions: z.boolean(),
  hr_talent: z.boolean(),
  users: z.boolean(),
  tools: z.boolean(),
  tenant_settings: z.boolean(),
  settings: z.boolean(),
  settings_branding: z.boolean(),
  settings_department_emails: z.boolean(),
  audit_logs: z.boolean(),
  support: z.boolean(),
}).partial(); // nuevos campos de visibilidad no rompen

export const DepartmentSchema = z.object({
  id: z.number(),
  tenant_id: z.number(),
  name: z.string(),
  description: z.string().nullable().optional(),
  manager_id: z.number().nullable().optional(),
  is_active: z.boolean(),
  created_at: z.string(),
  project_allocation_percentage: z.number().nullable().optional(),
  menu_visibility: DepartmentMenuVisibilitySchema.optional(),
  can_create_comparative: z.boolean().optional(),
  can_edit_comparative: z.boolean().optional(),
  can_delete_comparative: z.boolean().optional(),
  can_approve_comparative: z.boolean().optional(),
  can_reject_comparative: z.boolean().optional(),
  can_view_contract: z.boolean().optional(),
  can_edit_contract: z.boolean().optional(),
  can_regenerate_contract: z.boolean().optional(),
  can_approve_contract: z.boolean().optional(),
  can_reject_contract: z.boolean().optional(),
  can_view_worksite: z.boolean().optional(),
  can_edit_worksite: z.boolean().optional(),
  can_view_provider: z.boolean().optional(),
  can_edit_provider: z.boolean().optional(),
});

export const EmployeeProfileSchema = z.object({
  id: z.number(),
  tenant_id: z.number(),
  user_id: z.number().nullable().optional(),
  first_name: z.string().nullable().optional(),
  last_name: z.string().nullable().optional(),
  full_name: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  hourly_rate: z.number().nullable().optional(),
  available_hours: z.number().nullable().optional(),
  availability_percentage: z.number().nullable().optional(),
  position_id: z.number().nullable().optional(),
  employment_type: z.string(),
  hire_date: z.string().nullable().optional(),
  end_date: z.string().nullable().optional(),
  is_active: z.boolean().optional(),
});

export type Department = z.infer<typeof DepartmentSchema>;
export type EmployeeProfile = z.infer<typeof EmployeeProfileSchema>;
